// Code generated by protoc-gen-go. DO NOT EDIT.
// source: avoid.proto

package nebula

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHostInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostInfoRequest) Reset()         { *m = GetHostInfoRequest{} }
func (m *GetHostInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostInfoRequest) ProtoMessage()    {}
func (*GetHostInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e43cfd81e3b6e501, []int{0}
}

func (m *GetHostInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostInfoRequest.Unmarshal(m, b)
}
func (m *GetHostInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetHostInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostInfoRequest.Merge(m, src)
}
func (m *GetHostInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostInfoRequest.Size(m)
}
func (m *GetHostInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostInfoRequest proto.InternalMessageInfo

type GetHostInfoResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostInfoResponse) Reset()         { *m = GetHostInfoResponse{} }
func (m *GetHostInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostInfoResponse) ProtoMessage()    {}
func (*GetHostInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e43cfd81e3b6e501, []int{1}
}

func (m *GetHostInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostInfoResponse.Unmarshal(m, b)
}
func (m *GetHostInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetHostInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostInfoResponse.Merge(m, src)
}
func (m *GetHostInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetHostInfoResponse.Size(m)
}
func (m *GetHostInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostInfoResponse proto.InternalMessageInfo

func (m *GetHostInfoResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHostInfoRequest)(nil), "nebula.GetHostInfoRequest")
	proto.RegisterType((*GetHostInfoResponse)(nil), "nebula.GetHostInfoResponse")
}

func init() { proto.RegisterFile("avoid.proto", fileDescriptor_e43cfd81e3b6e501) }

var fileDescriptor_e43cfd81e3b6e501 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0xcb, 0xcf,
	0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4b, 0x4d, 0x2a, 0xcd, 0x49, 0x54,
	0x12, 0xe1, 0x12, 0x72, 0x4f, 0x2d, 0xf1, 0xc8, 0x2f, 0x2e, 0xf1, 0xcc, 0x4b, 0xcb, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe4, 0x12, 0x46, 0x11, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x15, 0x92, 0xe2, 0xe2, 0x28, 0x82, 0xb2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0x7c, 0xa3, 0x40, 0x2e, 0x56, 0x47, 0x90, 0xf9, 0x42, 0x1e, 0x5c, 0xdc, 0x48, 0x7a, 0x85, 0xa4,
	0xf4, 0x20, 0x36, 0xe9, 0x61, 0x5a, 0x23, 0x25, 0x8d, 0x55, 0x0e, 0x62, 0xa0, 0x12, 0x83, 0x93,
	0x74, 0x94, 0x64, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x71, 0x4e,
	0x62, 0x72, 0x76, 0x46, 0xa1, 0x3e, 0x44, 0x4b, 0x12, 0x1b, 0xd8, 0x1f, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xfa, 0xbf, 0x8e, 0x02, 0xd6, 0x00, 0x00, 0x00,
}
