// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: avoid.proto

package nebula

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Avoid_GetHostInfo_FullMethodName = "/nebula.Avoid/GetHostInfo"
)

// AvoidClient is the client API for Avoid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvoidClient interface {
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
}

type avoidClient struct {
	cc grpc.ClientConnInterface
}

func NewAvoidClient(cc grpc.ClientConnInterface) AvoidClient {
	return &avoidClient{cc}
}

func (c *avoidClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, Avoid_GetHostInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvoidServer is the server API for Avoid service.
// All implementations must embed UnimplementedAvoidServer
// for forward compatibility
type AvoidServer interface {
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	mustEmbedUnimplementedAvoidServer()
}

// UnimplementedAvoidServer must be embedded to have forward compatible implementations.
type UnimplementedAvoidServer struct {
}

func (UnimplementedAvoidServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedAvoidServer) mustEmbedUnimplementedAvoidServer() {}

// UnsafeAvoidServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvoidServer will
// result in compilation errors.
type UnsafeAvoidServer interface {
	mustEmbedUnimplementedAvoidServer()
}

func RegisterAvoidServer(s grpc.ServiceRegistrar, srv AvoidServer) {
	s.RegisterService(&Avoid_ServiceDesc, srv)
}

func _Avoid_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avoid_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Avoid_ServiceDesc is the grpc.ServiceDesc for Avoid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Avoid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebula.Avoid",
	HandlerType: (*AvoidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHostInfo",
			Handler:    _Avoid_GetHostInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avoid.proto",
}
