etcd:
 address: 192.168.200.200
 port: 2379
 timeout: 3000000000
 tls:
   key: /etc/etcd/db-key.pem
   cert: /etc/etcd/db.pem
   cacert: /etc/etcd/ca.pem

client:
  eps:
    - address: 192.168.200.200
      port: 55554
      timeout: 3000000000
  identity: lighthouse
