// Code generated by protoc-gen-go. DO NOT EDIT.
// source: avoid/avoid.proto

package avoid

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectionReply_New int32

const (
	ConnectionReply_None       ConnectionReply_New = 0
	ConnectionReply_Lighthouse ConnectionReply_New = 1
	ConnectionReply_Endpoint   ConnectionReply_New = 2
	ConnectionReply_Radio      ConnectionReply_New = 3
	ConnectionReply_Network    ConnectionReply_New = 4
)

var ConnectionReply_New_name = map[int32]string{
	0: "None",
	1: "Lighthouse",
	2: "Endpoint",
	3: "Radio",
	4: "Network",
}

var ConnectionReply_New_value = map[string]int32{
	"None":       0,
	"Lighthouse": 1,
	"Endpoint":   2,
	"Radio":      3,
	"Network":    4,
}

func (x ConnectionReply_New) String() string {
	return proto.EnumName(ConnectionReply_New_name, int32(x))
}

func (ConnectionReply_New) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{15, 0}
}

type ConnectionReply_ServingStatus int32

const (
	ConnectionReply_UNKNOWN         ConnectionReply_ServingStatus = 0
	ConnectionReply_SERVING         ConnectionReply_ServingStatus = 1
	ConnectionReply_NOT_SERVING     ConnectionReply_ServingStatus = 2
	ConnectionReply_SERVICE_UNKNOWN ConnectionReply_ServingStatus = 3
)

var ConnectionReply_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
	3: "SERVICE_UNKNOWN",
}

var ConnectionReply_ServingStatus_value = map[string]int32{
	"UNKNOWN":         0,
	"SERVING":         1,
	"NOT_SERVING":     2,
	"SERVICE_UNKNOWN": 3,
}

func (x ConnectionReply_ServingStatus) String() string {
	return proto.EnumName(ConnectionReply_ServingStatus_name, int32(x))
}

func (ConnectionReply_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{15, 1}
}

type ShutdownRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{0}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

func (m *ShutdownRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ShutdownReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownReply) Reset()         { *m = ShutdownReply{} }
func (m *ShutdownReply) String() string { return proto.CompactTextString(m) }
func (*ShutdownReply) ProtoMessage()    {}
func (*ShutdownReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{1}
}

func (m *ShutdownReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownReply.Unmarshal(m, b)
}
func (m *ShutdownReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownReply.Marshal(b, m, deterministic)
}
func (m *ShutdownReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownReply.Merge(m, src)
}
func (m *ShutdownReply) XXX_Size() int {
	return xxx_messageInfo_ShutdownReply.Size(m)
}
func (m *ShutdownReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownReply.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownReply proto.InternalMessageInfo

type ConnInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ran                  string   `protobuf:"bytes,2,opt,name=ran,proto3" json:"ran,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Endpoint             string   `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Network              string   `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	User                 string   `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	Duration             int64    `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Lastseen             int64    `protobuf:"varint,8,opt,name=lastseen,proto3" json:"lastseen,omitempty"`
	Download             int64    `protobuf:"varint,9,opt,name=download,proto3" json:"download,omitempty"`
	Upload               int64    `protobuf:"varint,10,opt,name=upload,proto3" json:"upload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnInfo) Reset()         { *m = ConnInfo{} }
func (m *ConnInfo) String() string { return proto.CompactTextString(m) }
func (*ConnInfo) ProtoMessage()    {}
func (*ConnInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{2}
}

func (m *ConnInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnInfo.Unmarshal(m, b)
}
func (m *ConnInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnInfo.Marshal(b, m, deterministic)
}
func (m *ConnInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnInfo.Merge(m, src)
}
func (m *ConnInfo) XXX_Size() int {
	return xxx_messageInfo_ConnInfo.Size(m)
}
func (m *ConnInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnInfo proto.InternalMessageInfo

func (m *ConnInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConnInfo) GetRan() string {
	if m != nil {
		return m.Ran
	}
	return ""
}

func (m *ConnInfo) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ConnInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ConnInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *ConnInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ConnInfo) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *ConnInfo) GetLastseen() int64 {
	if m != nil {
		return m.Lastseen
	}
	return 0
}

func (m *ConnInfo) GetDownload() int64 {
	if m != nil {
		return m.Download
	}
	return 0
}

func (m *ConnInfo) GetUpload() int64 {
	if m != nil {
		return m.Upload
	}
	return 0
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListReply struct {
	Info                 []*ConnInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{4}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetInfo() []*ConnInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Statistics struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Connectedran         string   `protobuf:"bytes,2,opt,name=connectedran,proto3" json:"connectedran,omitempty"`
	Nearbyran            string   `protobuf:"bytes,3,opt,name=nearbyran,proto3" json:"nearbyran,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Endpoint             string   `protobuf:"bytes,5,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Network              string   `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	User                 string   `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Duration             int64    `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Lastseen             int64    `protobuf:"varint,9,opt,name=lastseen,proto3" json:"lastseen,omitempty"`
	Download             int64    `protobuf:"varint,10,opt,name=download,proto3" json:"download,omitempty"`
	Upload               int64    `protobuf:"varint,11,opt,name=upload,proto3" json:"upload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{5}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Statistics) GetConnectedran() string {
	if m != nil {
		return m.Connectedran
	}
	return ""
}

func (m *Statistics) GetNearbyran() string {
	if m != nil {
		return m.Nearbyran
	}
	return ""
}

func (m *Statistics) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Statistics) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Statistics) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Statistics) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Statistics) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Statistics) GetLastseen() int64 {
	if m != nil {
		return m.Lastseen
	}
	return 0
}

func (m *Statistics) GetDownload() int64 {
	if m != nil {
		return m.Download
	}
	return 0
}

func (m *Statistics) GetUpload() int64 {
	if m != nil {
		return m.Upload
	}
	return 0
}

type StatsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{6}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

func (m *StatsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StatsReply struct {
	Stats                []*Statistics `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StatsReply) Reset()         { *m = StatsReply{} }
func (m *StatsReply) String() string { return proto.CompactTextString(m) }
func (*StatsReply) ProtoMessage()    {}
func (*StatsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{7}
}

func (m *StatsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsReply.Unmarshal(m, b)
}
func (m *StatsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsReply.Marshal(b, m, deterministic)
}
func (m *StatsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsReply.Merge(m, src)
}
func (m *StatsReply) XXX_Size() int {
	return xxx_messageInfo_StatsReply.Size(m)
}
func (m *StatsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatsReply proto.InternalMessageInfo

func (m *StatsReply) GetStats() []*Statistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

type ConnectionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{8}
}

func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(m, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConnectionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type MigrateRequest struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Migrate              *ConnectionReply `protobuf:"bytes,2,opt,name=migrate,proto3" json:"migrate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MigrateRequest) Reset()         { *m = MigrateRequest{} }
func (m *MigrateRequest) String() string { return proto.CompactTextString(m) }
func (*MigrateRequest) ProtoMessage()    {}
func (*MigrateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{9}
}

func (m *MigrateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateRequest.Unmarshal(m, b)
}
func (m *MigrateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateRequest.Marshal(b, m, deterministic)
}
func (m *MigrateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateRequest.Merge(m, src)
}
func (m *MigrateRequest) XXX_Size() int {
	return xxx_messageInfo_MigrateRequest.Size(m)
}
func (m *MigrateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateRequest proto.InternalMessageInfo

func (m *MigrateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MigrateRequest) GetMigrate() *ConnectionReply {
	if m != nil {
		return m.Migrate
	}
	return nil
}

type MigrateReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MigrateReply) Reset()         { *m = MigrateReply{} }
func (m *MigrateReply) String() string { return proto.CompactTextString(m) }
func (*MigrateReply) ProtoMessage()    {}
func (*MigrateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{10}
}

func (m *MigrateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MigrateReply.Unmarshal(m, b)
}
func (m *MigrateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MigrateReply.Marshal(b, m, deterministic)
}
func (m *MigrateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MigrateReply.Merge(m, src)
}
func (m *MigrateReply) XXX_Size() int {
	return xxx_messageInfo_MigrateReply.Size(m)
}
func (m *MigrateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MigrateReply.DiscardUnknown(m)
}

var xxx_messageInfo_MigrateReply proto.InternalMessageInfo

type RegisterRequest struct {
	Req                  string   `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{11}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetReq() string {
	if m != nil {
		return m.Req
	}
	return ""
}

type RegisterReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{12}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// TODO: protobuf the message
type HealthRequest struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{13}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

func (m *HealthRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type HealthReply struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthReply) Reset()         { *m = HealthReply{} }
func (m *HealthReply) String() string { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()    {}
func (*HealthReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{14}
}

func (m *HealthReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthReply.Unmarshal(m, b)
}
func (m *HealthReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthReply.Marshal(b, m, deterministic)
}
func (m *HealthReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthReply.Merge(m, src)
}
func (m *HealthReply) XXX_Size() int {
	return xxx_messageInfo_HealthReply.Size(m)
}
func (m *HealthReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthReply proto.InternalMessageInfo

func (m *HealthReply) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type ConnectionReply struct {
	Connection           ConnectionReply_New           `protobuf:"varint,1,opt,name=Connection,proto3,enum=avoid.ConnectionReply_New" json:"Connection,omitempty"`
	Value                string                        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Status               ConnectionReply_ServingStatus `protobuf:"varint,3,opt,name=status,proto3,enum=avoid.ConnectionReply_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ConnectionReply) Reset()         { *m = ConnectionReply{} }
func (m *ConnectionReply) String() string { return proto.CompactTextString(m) }
func (*ConnectionReply) ProtoMessage()    {}
func (*ConnectionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7044f2f819b3620, []int{15}
}

func (m *ConnectionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionReply.Unmarshal(m, b)
}
func (m *ConnectionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionReply.Marshal(b, m, deterministic)
}
func (m *ConnectionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionReply.Merge(m, src)
}
func (m *ConnectionReply) XXX_Size() int {
	return xxx_messageInfo_ConnectionReply.Size(m)
}
func (m *ConnectionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionReply proto.InternalMessageInfo

func (m *ConnectionReply) GetConnection() ConnectionReply_New {
	if m != nil {
		return m.Connection
	}
	return ConnectionReply_None
}

func (m *ConnectionReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ConnectionReply) GetStatus() ConnectionReply_ServingStatus {
	if m != nil {
		return m.Status
	}
	return ConnectionReply_UNKNOWN
}

func init() {
	proto.RegisterEnum("avoid.ConnectionReply_New", ConnectionReply_New_name, ConnectionReply_New_value)
	proto.RegisterEnum("avoid.ConnectionReply_ServingStatus", ConnectionReply_ServingStatus_name, ConnectionReply_ServingStatus_value)
	proto.RegisterType((*ShutdownRequest)(nil), "avoid.ShutdownRequest")
	proto.RegisterType((*ShutdownReply)(nil), "avoid.ShutdownReply")
	proto.RegisterType((*ConnInfo)(nil), "avoid.ConnInfo")
	proto.RegisterType((*ListRequest)(nil), "avoid.ListRequest")
	proto.RegisterType((*ListReply)(nil), "avoid.ListReply")
	proto.RegisterType((*Statistics)(nil), "avoid.Statistics")
	proto.RegisterType((*StatsRequest)(nil), "avoid.StatsRequest")
	proto.RegisterType((*StatsReply)(nil), "avoid.StatsReply")
	proto.RegisterType((*ConnectionRequest)(nil), "avoid.ConnectionRequest")
	proto.RegisterType((*MigrateRequest)(nil), "avoid.MigrateRequest")
	proto.RegisterType((*MigrateReply)(nil), "avoid.MigrateReply")
	proto.RegisterType((*RegisterRequest)(nil), "avoid.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "avoid.RegisterReply")
	proto.RegisterType((*HealthRequest)(nil), "avoid.HealthRequest")
	proto.RegisterType((*HealthReply)(nil), "avoid.HealthReply")
	proto.RegisterType((*ConnectionReply)(nil), "avoid.ConnectionReply")
}

func init() {
	proto.RegisterFile("avoid/avoid.proto", fileDescriptor_f7044f2f819b3620)
}

var fileDescriptor_f7044f2f819b3620 = []byte{
	// 815 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xb6, 0xfc, 0xef, 0xe3, 0x1f, 0x29, 0x4c, 0x57, 0x08, 0xc6, 0x80, 0xa5, 0xcc, 0x8a, 0xe5,
	0x2a, 0x09, 0xbc, 0x0d, 0x43, 0x8b, 0x15, 0x18, 0x16, 0x04, 0x5d, 0xb1, 0x4e, 0x01, 0xe4, 0xac,
	0x05, 0x76, 0x53, 0x30, 0x32, 0x6b, 0x69, 0x51, 0x48, 0x47, 0xa4, 0x62, 0xf8, 0x9d, 0xf6, 0x02,
	0x7b, 0xa1, 0x3d, 0xc4, 0xae, 0x06, 0x92, 0xa2, 0x6c, 0x79, 0xb6, 0x6f, 0x0c, 0x7e, 0xe7, 0x7c,
	0xe7, 0x88, 0xfc, 0xf8, 0x1d, 0x13, 0x8e, 0xc8, 0x13, 0x4f, 0x66, 0x17, 0xfa, 0xf7, 0x7c, 0x91,
	0x71, 0xc9, 0x51, 0x4b, 0x03, 0xfc, 0x12, 0xdc, 0x69, 0x9c, 0xcb, 0x19, 0x5f, 0xb2, 0x90, 0x3e,
	0xe6, 0x54, 0x48, 0x84, 0xa0, 0xc9, 0xc8, 0x03, 0xf5, 0x9d, 0x13, 0xe7, 0xac, 0x17, 0xea, 0x35,
	0x76, 0x61, 0xb8, 0xa6, 0x2d, 0xd2, 0x15, 0xfe, 0xd7, 0x81, 0xee, 0x15, 0x67, 0xec, 0x1d, 0xfb,
	0xcc, 0x77, 0x55, 0x20, 0x0f, 0x1a, 0x19, 0x61, 0x7e, 0x5d, 0x87, 0xd4, 0x52, 0xb1, 0x16, 0x44,
	0xc6, 0x7e, 0xc3, 0xb0, 0xd4, 0x1a, 0x8d, 0xa1, 0x4b, 0xd9, 0x6c, 0xc1, 0x13, 0x26, 0xfd, 0xa6,
	0x8e, 0x97, 0x18, 0xf9, 0xd0, 0x61, 0x54, 0x2e, 0x79, 0x76, 0xef, 0xb7, 0x74, 0xca, 0x42, 0xd5,
	0x29, 0x17, 0x34, 0xf3, 0xdb, 0xa6, 0x93, 0x5a, 0xab, 0x4e, 0xb3, 0x3c, 0x23, 0x32, 0xe1, 0xcc,
	0xef, 0x9c, 0x38, 0x67, 0x8d, 0xb0, 0xc4, 0x2a, 0x97, 0x12, 0x21, 0x05, 0xa5, 0xcc, 0xef, 0x9a,
	0x9c, 0xc5, 0xba, 0x8e, 0x2f, 0x59, 0xca, 0xc9, 0xcc, 0xef, 0x15, 0x75, 0x05, 0x46, 0xcf, 0xa1,
	0x9d, 0x2f, 0x74, 0x06, 0x74, 0xa6, 0x40, 0x78, 0x08, 0xfd, 0xf7, 0x89, 0x90, 0x85, 0x60, 0xf8,
	0x12, 0x7a, 0x06, 0x2e, 0xd2, 0x15, 0x3a, 0x85, 0x66, 0xc2, 0x3e, 0x73, 0xdf, 0x39, 0x69, 0x9c,
	0xf5, 0x27, 0xee, 0xb9, 0xd1, 0xdc, 0x4a, 0x15, 0xea, 0x24, 0xfe, 0xab, 0x0e, 0x30, 0x95, 0x44,
	0x26, 0x42, 0x26, 0x91, 0xd8, 0xa9, 0x1f, 0x86, 0x41, 0xc4, 0x19, 0xa3, 0x91, 0xa4, 0xb3, 0xb5,
	0x90, 0x95, 0x18, 0xfa, 0x12, 0x7a, 0x8c, 0x92, 0xec, 0x6e, 0xa5, 0x08, 0x46, 0xd6, 0x75, 0xa0,
	0xd4, 0xbb, 0xb9, 0x47, 0xef, 0xd6, 0x7e, 0xbd, 0xdb, 0xbb, 0xf5, 0xee, 0xec, 0xd1, 0xbb, 0x7b,
	0x40, 0xef, 0xde, 0x01, 0xbd, 0x61, 0xaf, 0xde, 0xfd, 0x8a, 0xde, 0x18, 0x06, 0x4a, 0x2d, 0x71,
	0xc8, 0xa1, 0xdf, 0x1b, 0x45, 0x85, 0xb9, 0x85, 0x6f, 0xa0, 0x25, 0x14, 0x2a, 0xae, 0xe1, 0xa8,
	0xb8, 0x86, 0xb5, 0xe6, 0xa1, 0xc9, 0xe3, 0x37, 0x70, 0x74, 0x65, 0x24, 0x4d, 0xf8, 0xa1, 0x09,
	0x40, 0xcf, 0xa0, 0x25, 0xf9, 0x3d, 0xb5, 0x17, 0x61, 0x00, 0xfe, 0x00, 0xa3, 0xdf, 0x92, 0x79,
	0x46, 0x24, 0x3d, 0x54, 0x7b, 0x09, 0x9d, 0x07, 0xc3, 0xd2, 0xd5, 0xfd, 0xc9, 0xf3, 0x0d, 0x5b,
	0xd8, 0x4f, 0x2f, 0xd2, 0x55, 0x68, 0x69, 0x78, 0x04, 0x83, 0xb2, 0xaf, 0x1a, 0xb7, 0x53, 0x70,
	0x43, 0x3a, 0x4f, 0x84, 0xa4, 0x99, 0xfd, 0x90, 0x1a, 0x30, 0xfa, 0x58, 0x7c, 0x47, 0x2d, 0xf1,
	0x4b, 0x18, 0xae, 0x49, 0x4a, 0x85, 0x72, 0xcf, 0xce, 0xe6, 0x9e, 0x4f, 0x61, 0xf8, 0x0b, 0x25,
	0xa9, 0x8c, 0x37, 0xb6, 0xfc, 0xa7, 0xe0, 0x96, 0xa5, 0xd7, 0xf8, 0x05, 0xf4, 0x2d, 0x49, 0x75,
	0xda, 0x45, 0xf9, 0xbb, 0x0e, 0xee, 0xd6, 0x01, 0xd0, 0x6b, 0x80, 0x75, 0x48, 0xb3, 0x47, 0x93,
	0xf1, 0xee, 0xc3, 0x9e, 0x07, 0x74, 0x19, 0x6e, 0xb0, 0xd5, 0x6e, 0x9f, 0x48, 0x9a, 0x53, 0xab,
	0xb0, 0x06, 0xe8, 0x47, 0x68, 0xab, 0x9b, 0xca, 0x85, 0x36, 0xf8, 0x68, 0xf2, 0xf5, 0x9e, 0x6e,
	0x53, 0x9a, 0x3d, 0x25, 0x6c, 0x3e, 0xd5, 0xdc, 0xb0, 0xa8, 0xc1, 0xd7, 0xd0, 0x08, 0xe8, 0x12,
	0x75, 0xa1, 0x19, 0x70, 0x46, 0xbd, 0x1a, 0x1a, 0x01, 0xbc, 0x4f, 0xe6, 0xb1, 0x8c, 0x79, 0x2e,
	0xa8, 0xe7, 0xa0, 0x01, 0x74, 0xaf, 0x8b, 0x01, 0xf0, 0xea, 0xa8, 0x07, 0xad, 0x90, 0xcc, 0x12,
	0xee, 0x35, 0x50, 0x1f, 0x3a, 0x81, 0xb1, 0xbf, 0xd7, 0xc4, 0x37, 0x30, 0xac, 0xf4, 0x57, 0xd9,
	0xdf, 0x83, 0x5f, 0x83, 0x9b, 0x8f, 0x81, 0x57, 0x53, 0x60, 0x7a, 0x1d, 0x7e, 0x78, 0x17, 0xbc,
	0xf5, 0x1c, 0xe4, 0x42, 0x3f, 0xb8, 0xb9, 0xfd, 0x64, 0x03, 0x75, 0x74, 0x0c, 0xae, 0x06, 0x57,
	0xd7, 0x9f, 0x6c, 0x49, 0x63, 0xf2, 0x4f, 0x03, 0xda, 0xb7, 0x39, 0x63, 0x34, 0x45, 0xaf, 0xc0,
	0x55, 0xff, 0x1e, 0xeb, 0xf3, 0x08, 0x84, 0x8a, 0x33, 0x6e, 0xfc, 0xc9, 0x8c, 0xbd, 0x4a, 0x4c,
	0x79, 0xa2, 0x86, 0xbe, 0x83, 0xee, 0x5b, 0x2a, 0xb5, 0xed, 0xd1, 0xf1, 0x86, 0xc5, 0xed, 0xa0,
	0x8c, 0x8f, 0xaa, 0x41, 0x53, 0xf5, 0x03, 0x74, 0x0a, 0x6f, 0xa1, 0x2f, 0x8a, 0x7c, 0xd5, 0xc3,
	0xe3, 0xe3, 0xed, 0xb0, 0x29, 0x7c, 0x0d, 0x5d, 0xfb, 0x08, 0x20, 0xeb, 0xe0, 0xad, 0xc7, 0x63,
	0xfc, 0xec, 0x7f, 0xf1, 0xb2, 0xd6, 0x7a, 0xb3, 0xac, 0xdd, 0x72, 0x74, 0x59, 0x5b, 0x31, 0x31,
	0xae, 0xa1, 0x9f, 0x60, 0x70, 0xab, 0x9c, 0xab, 0x30, 0x89, 0x28, 0xf2, 0x77, 0x58, 0xe0, 0x70,
	0x87, 0x57, 0xd6, 0xcd, 0x57, 0x31, 0x8d, 0xee, 0x91, 0xa5, 0x55, 0xc6, 0x60, 0x8c, 0xb6, 0xa2,
	0xa6, 0xf4, 0x0d, 0xb4, 0x3e, 0x12, 0x19, 0xc5, 0x07, 0xbe, 0xba, 0x67, 0x9a, 0x71, 0xed, 0xd2,
	0xf9, 0xf9, 0xc5, 0x1f, 0x5f, 0xcd, 0x13, 0x19, 0xe7, 0x77, 0xe7, 0x11, 0x7f, 0xb8, 0x10, 0x29,
	0x89, 0xee, 0xe3, 0xc7, 0x0b, 0x46, 0xef, 0xf2, 0x94, 0x98, 0xf7, 0xf8, 0xae, 0xad, 0x1f, 0xe4,
	0x6f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x04, 0xa5, 0xe3, 0xa5, 0x07, 0x00, 0x00,
}
