// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: avoid/client.proto

package avoid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AvoidClient_Action_FullMethodName      = "/avoid.client.AvoidClient/Action"
	AvoidClient_HealthCheck_FullMethodName = "/avoid.client.AvoidClient/HealthCheck"
)

// AvoidClientClient is the client API for AvoidClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// From Actioneer or Handler TO UE
// The assumption is this service is specific to UE endpoints and incorporates
// the actions required to be taken by the avoid service.
type AvoidClientClient interface {
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ConnectionInfo, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
}

type avoidClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAvoidClientClient(cc grpc.ClientConnInterface) AvoidClientClient {
	return &avoidClientClient{cc}
}

func (c *avoidClientClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ConnectionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionInfo)
	err := c.cc.Invoke(ctx, AvoidClient_Action_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidClientClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, AvoidClient_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvoidClientServer is the server API for AvoidClient service.
// All implementations must embed UnimplementedAvoidClientServer
// for forward compatibility
//
// From Actioneer or Handler TO UE
// The assumption is this service is specific to UE endpoints and incorporates
// the actions required to be taken by the avoid service.
type AvoidClientServer interface {
	Action(context.Context, *ActionRequest) (*ConnectionInfo, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthReply, error)
	mustEmbedUnimplementedAvoidClientServer()
}

// UnimplementedAvoidClientServer must be embedded to have forward compatible implementations.
type UnimplementedAvoidClientServer struct {
}

func (UnimplementedAvoidClientServer) Action(context.Context, *ActionRequest) (*ConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (UnimplementedAvoidClientServer) HealthCheck(context.Context, *HealthRequest) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAvoidClientServer) mustEmbedUnimplementedAvoidClientServer() {}

// UnsafeAvoidClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvoidClientServer will
// result in compilation errors.
type UnsafeAvoidClientServer interface {
	mustEmbedUnimplementedAvoidClientServer()
}

func RegisterAvoidClientServer(s grpc.ServiceRegistrar, srv AvoidClientServer) {
	s.RegisterService(&AvoidClient_ServiceDesc, srv)
}

func _AvoidClient_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidClient_Action_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidClient_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidClient_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvoidClient_ServiceDesc is the grpc.ServiceDesc for AvoidClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvoidClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avoid.client.AvoidClient",
	HandlerType: (*AvoidClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Action",
			Handler:    _AvoidClient_Action_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AvoidClient_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avoid/client.proto",
}
