// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: avoid/client.proto

package avoid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AvoidClientClient is the client API for AvoidClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvoidClientClient interface {
	// client
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	TokenReplace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceReply, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*ConnectionInfo, error)
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ConnectionInfo, error)
}

type avoidClientClient struct {
	cc grpc.ClientConnInterface
}

func NewAvoidClientClient(cc grpc.ClientConnInterface) AvoidClientClient {
	return &avoidClientClient{cc}
}

func (c *avoidClientClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidClient/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidClientClient) TokenReplace(ctx context.Context, in *ReplaceRequest, opts ...grpc.CallOption) (*ReplaceReply, error) {
	out := new(ReplaceReply)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidClient/TokenReplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidClientClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*ConnectionInfo, error) {
	out := new(ConnectionInfo)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidClient/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidClientClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ConnectionInfo, error) {
	out := new(ConnectionInfo)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidClient/Action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvoidClientServer is the server API for AvoidClient service.
// All implementations must embed UnimplementedAvoidClientServer
// for forward compatibility
type AvoidClientServer interface {
	// client
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	TokenReplace(context.Context, *ReplaceRequest) (*ReplaceReply, error)
	HealthCheck(context.Context, *HealthRequest) (*ConnectionInfo, error)
	Action(context.Context, *ActionRequest) (*ConnectionInfo, error)
	mustEmbedUnimplementedAvoidClientServer()
}

// UnimplementedAvoidClientServer must be embedded to have forward compatible implementations.
type UnimplementedAvoidClientServer struct {
}

func (UnimplementedAvoidClientServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAvoidClientServer) TokenReplace(context.Context, *ReplaceRequest) (*ReplaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenReplace not implemented")
}
func (UnimplementedAvoidClientServer) HealthCheck(context.Context, *HealthRequest) (*ConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAvoidClientServer) Action(context.Context, *ActionRequest) (*ConnectionInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Action not implemented")
}
func (UnimplementedAvoidClientServer) mustEmbedUnimplementedAvoidClientServer() {}

// UnsafeAvoidClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvoidClientServer will
// result in compilation errors.
type UnsafeAvoidClientServer interface {
	mustEmbedUnimplementedAvoidClientServer()
}

func RegisterAvoidClientServer(s grpc.ServiceRegistrar, srv AvoidClientServer) {
	s.RegisterService(&AvoidClient_ServiceDesc, srv)
}

func _AvoidClient_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidClient/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidClient_TokenReplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).TokenReplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidClient/TokenReplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).TokenReplace(ctx, req.(*ReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidClient_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidClient/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidClient_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidClientServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidClient/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidClientServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvoidClient_ServiceDesc is the grpc.ServiceDesc for AvoidClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvoidClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avoid.client.AvoidClient",
	HandlerType: (*AvoidClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AvoidClient_Register_Handler,
		},
		{
			MethodName: "TokenReplace",
			Handler:    _AvoidClient_TokenReplace_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AvoidClient_HealthCheck_Handler,
		},
		{
			MethodName: "Action",
			Handler:    _AvoidClient_Action_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avoid/client.proto",
}
