syntax = "proto3";

package avoid.client;

import "avoid/messages.proto";

option go_package = "github.com/slackhq/nebula/avoid";

// From Actioneer or Handler TO UE
// The assumption is this service is specific to UE endpoints and incorporates
// the actions required to be taken by the avoid service.
service AvoidClient {
  rpc Action(avoid.messages.ActionRequest) returns (avoid.messages.ConnectionInfo) {}
  rpc HealthCheck (avoid.messages.HealthRequest) returns (avoid.messages.HealthReply) {}
}
