syntax = "proto3";

package avoid.manager;

import "avoid/messages.proto";

option go_package = "github.com/slackhq/nebula/avoid";

service AvoidManager {
  rpc ListConnections (ListRequest) returns (ListReply) {}
  rpc GetStats (StatsRequest) returns (avoid.messages.ConnectionInfo) {}
  rpc Disconnect (avoid.messages.ActionRequest) returns (avoid.messages.ConnectionInfo) {}
  rpc Migrate (avoid.messages.ActionRequest) returns (avoid.messages.ConnectionInfo) {}
}

message ListRequest {}
message ListReply {
  repeated avoid.messages.ConnectionInfo info = 1;
}

message StatsRequest {
  string name = 1;
}
