// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: avoid/manager.proto

package avoid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AvoidManager_ListConnections_FullMethodName = "/avoid.manager.AvoidManager/ListConnections"
	AvoidManager_GetStats_FullMethodName        = "/avoid.manager.AvoidManager/GetStats"
	AvoidManager_Migrate_FullMethodName         = "/avoid.manager.AvoidManager/Migrate"
	AvoidManager_Disconnect_FullMethodName      = "/avoid.manager.AvoidManager/Disconnect"
)

// AvoidManagerClient is the client API for AvoidManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvoidManagerClient interface {
	ListConnections(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error)
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error)
}

type avoidManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAvoidManagerClient(cc grpc.ClientConnInterface) AvoidManagerClient {
	return &avoidManagerClient{cc}
}

func (c *avoidManagerClient) ListConnections(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReply)
	err := c.cc.Invoke(ctx, AvoidManager_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidManagerClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsReply)
	err := c.cc.Invoke(ctx, AvoidManager_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidManagerClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateReply)
	err := c.cc.Invoke(ctx, AvoidManager_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidManagerClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectReply)
	err := c.cc.Invoke(ctx, AvoidManager_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvoidManagerServer is the server API for AvoidManager service.
// All implementations must embed UnimplementedAvoidManagerServer
// for forward compatibility
type AvoidManagerServer interface {
	ListConnections(context.Context, *ListRequest) (*ListReply, error)
	GetStats(context.Context, *StatsRequest) (*StatsReply, error)
	Migrate(context.Context, *MigrateRequest) (*MigrateReply, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error)
	mustEmbedUnimplementedAvoidManagerServer()
}

// UnimplementedAvoidManagerServer must be embedded to have forward compatible implementations.
type UnimplementedAvoidManagerServer struct {
}

func (UnimplementedAvoidManagerServer) ListConnections(context.Context, *ListRequest) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedAvoidManagerServer) GetStats(context.Context, *StatsRequest) (*StatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAvoidManagerServer) Migrate(context.Context, *MigrateRequest) (*MigrateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedAvoidManagerServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedAvoidManagerServer) mustEmbedUnimplementedAvoidManagerServer() {}

// UnsafeAvoidManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvoidManagerServer will
// result in compilation errors.
type UnsafeAvoidManagerServer interface {
	mustEmbedUnimplementedAvoidManagerServer()
}

func RegisterAvoidManagerServer(s grpc.ServiceRegistrar, srv AvoidManagerServer) {
	s.RegisterService(&AvoidManager_ServiceDesc, srv)
}

func _AvoidManager_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidManagerServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidManager_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidManagerServer).ListConnections(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidManager_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidManagerServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidManager_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidManagerServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidManager_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidManagerServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidManager_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidManagerServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidManager_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidManagerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvoidManager_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidManagerServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvoidManager_ServiceDesc is the grpc.ServiceDesc for AvoidManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvoidManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avoid.manager.AvoidManager",
	HandlerType: (*AvoidManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnections",
			Handler:    _AvoidManager_ListConnections_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _AvoidManager_GetStats_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _AvoidManager_Migrate_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _AvoidManager_Disconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avoid/manager.proto",
}
