// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: avoid/messages.proto

package avoid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionMessage_ConnType int32

const (
	ActionMessage_NONE       ActionMessage_ConnType = 0
	ActionMessage_LIGHTHOUSE ActionMessage_ConnType = 1
	ActionMessage_ENDPOINT   ActionMessage_ConnType = 2
	ActionMessage_RADIO      ActionMessage_ConnType = 3
	ActionMessage_NETWORK    ActionMessage_ConnType = 4
	ActionMessage_RELAY      ActionMessage_ConnType = 5
)

// Enum value maps for ActionMessage_ConnType.
var (
	ActionMessage_ConnType_name = map[int32]string{
		0: "NONE",
		1: "LIGHTHOUSE",
		2: "ENDPOINT",
		3: "RADIO",
		4: "NETWORK",
		5: "RELAY",
	}
	ActionMessage_ConnType_value = map[string]int32{
		"NONE":       0,
		"LIGHTHOUSE": 1,
		"ENDPOINT":   2,
		"RADIO":      3,
		"NETWORK":    4,
		"RELAY":      5,
	}
)

func (x ActionMessage_ConnType) Enum() *ActionMessage_ConnType {
	p := new(ActionMessage_ConnType)
	*p = x
	return p
}

func (x ActionMessage_ConnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionMessage_ConnType) Descriptor() protoreflect.EnumDescriptor {
	return file_avoid_messages_proto_enumTypes[0].Descriptor()
}

func (ActionMessage_ConnType) Type() protoreflect.EnumType {
	return &file_avoid_messages_proto_enumTypes[0]
}

func (x ActionMessage_ConnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionMessage_ConnType.Descriptor instead.
func (ActionMessage_ConnType) EnumDescriptor() ([]byte, []int) {
	return file_avoid_messages_proto_rawDescGZIP(), []int{1, 0}
}

type ActionMessage_Action int32

const (
	ActionMessage_UNDEFINED  ActionMessage_Action = 0
	ActionMessage_MIGRATE    ActionMessage_Action = 1
	ActionMessage_DISCONNECT ActionMessage_Action = 2
	ActionMessage_APPEND     ActionMessage_Action = 3
	ActionMessage_PRUNE      ActionMessage_Action = 4
	ActionMessage_FLUSH      ActionMessage_Action = 5
	ActionMessage_STATISTICS ActionMessage_Action = 6
)

// Enum value maps for ActionMessage_Action.
var (
	ActionMessage_Action_name = map[int32]string{
		0: "UNDEFINED",
		1: "MIGRATE",
		2: "DISCONNECT",
		3: "APPEND",
		4: "PRUNE",
		5: "FLUSH",
		6: "STATISTICS",
	}
	ActionMessage_Action_value = map[string]int32{
		"UNDEFINED":  0,
		"MIGRATE":    1,
		"DISCONNECT": 2,
		"APPEND":     3,
		"PRUNE":      4,
		"FLUSH":      5,
		"STATISTICS": 6,
	}
)

func (x ActionMessage_Action) Enum() *ActionMessage_Action {
	p := new(ActionMessage_Action)
	*p = x
	return p
}

func (x ActionMessage_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionMessage_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_avoid_messages_proto_enumTypes[1].Descriptor()
}

func (ActionMessage_Action) Type() protoreflect.EnumType {
	return &file_avoid_messages_proto_enumTypes[1]
}

func (x ActionMessage_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionMessage_Action.Descriptor instead.
func (ActionMessage_Action) EnumDescriptor() ([]byte, []int) {
	return file_avoid_messages_proto_rawDescGZIP(), []int{1, 1}
}

type ConnectionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ran      string `protobuf:"bytes,2,opt,name=ran,proto3" json:"ran,omitempty"`
	Path     string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Endpoint string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Network  string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Relay    string `protobuf:"bytes,6,opt,name=relay,proto3" json:"relay,omitempty"`
	User     string `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Duration int64  `protobuf:"varint,8,opt,name=duration,proto3" json:"duration,omitempty"`
	Lastseen int64  `protobuf:"varint,9,opt,name=lastseen,proto3" json:"lastseen,omitempty"`
	Download int64  `protobuf:"varint,10,opt,name=download,proto3" json:"download,omitempty"`
	Upload   int64  `protobuf:"varint,11,opt,name=upload,proto3" json:"upload,omitempty"`
	Error    bool   `protobuf:"varint,12,opt,name=error,proto3" json:"error,omitempty"`
	ErrMsg   string `protobuf:"bytes,13,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avoid_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_avoid_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_avoid_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionInfo) GetRan() string {
	if x != nil {
		return x.Ran
	}
	return ""
}

func (x *ConnectionInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConnectionInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConnectionInfo) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ConnectionInfo) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *ConnectionInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ConnectionInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ConnectionInfo) GetLastseen() int64 {
	if x != nil {
		return x.Lastseen
	}
	return 0
}

func (x *ConnectionInfo) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *ConnectionInfo) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *ConnectionInfo) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ConnectionInfo) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type ActionMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connection ActionMessage_ConnType `protobuf:"varint,1,opt,name=connection,proto3,enum=avoid.messages.ActionMessage_ConnType" json:"connection,omitempty"`
	Action     ActionMessage_Action   `protobuf:"varint,2,opt,name=action,proto3,enum=avoid.messages.ActionMessage_Action" json:"action,omitempty"`
	Uuid       string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ActionMessage) Reset() {
	*x = ActionMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avoid_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionMessage) ProtoMessage() {}

func (x *ActionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_avoid_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionMessage.ProtoReflect.Descriptor instead.
func (*ActionMessage) Descriptor() ([]byte, []int) {
	return file_avoid_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ActionMessage) GetConnection() ActionMessage_ConnType {
	if x != nil {
		return x.Connection
	}
	return ActionMessage_NONE
}

func (x *ActionMessage) GetAction() ActionMessage_Action {
	if x != nil {
		return x.Action
	}
	return ActionMessage_UNDEFINED
}

func (x *ActionMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_avoid_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avoid_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_avoid_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ActionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ActionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_avoid_messages_proto protoreflect.FileDescriptor

var file_avoid_messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xc4, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x61, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x73, 0x65, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x22, 0xe8, 0x02,
	0x0a, 0x0d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x46, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x55, 0x0a, 0x08, 0x43, 0x6f, 0x6e,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x4c, 0x49, 0x47, 0x48, 0x54, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x45, 0x4e, 0x44, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x41, 0x44, 0x49, 0x4f, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57,
	0x4f, 0x52, 0x4b, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x4c, 0x41, 0x59, 0x10, 0x05,
	0x22, 0x66, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x49, 0x47,
	0x52, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e,
	0x4e, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x52, 0x55, 0x4e, 0x45, 0x10, 0x04, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54,
	0x49, 0x53, 0x54, 0x49, 0x43, 0x53, 0x10, 0x06, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6c, 0x61, 0x63, 0x6b, 0x68, 0x71, 0x2f, 0x6e, 0x65, 0x62,
	0x75, 0x6c, 0x61, 0x2f, 0x61, 0x76, 0x6f, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_avoid_messages_proto_rawDescOnce sync.Once
	file_avoid_messages_proto_rawDescData = file_avoid_messages_proto_rawDesc
)

func file_avoid_messages_proto_rawDescGZIP() []byte {
	file_avoid_messages_proto_rawDescOnce.Do(func() {
		file_avoid_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_avoid_messages_proto_rawDescData)
	})
	return file_avoid_messages_proto_rawDescData
}

var file_avoid_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_avoid_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_avoid_messages_proto_goTypes = []interface{}{
	(ActionMessage_ConnType)(0), // 0: avoid.messages.ActionMessage.ConnType
	(ActionMessage_Action)(0),   // 1: avoid.messages.ActionMessage.Action
	(*ConnectionInfo)(nil),      // 2: avoid.messages.ConnectionInfo
	(*ActionMessage)(nil),       // 3: avoid.messages.ActionMessage
	(*ActionResponse)(nil),      // 4: avoid.messages.ActionResponse
}
var file_avoid_messages_proto_depIdxs = []int32{
	0, // 0: avoid.messages.ActionMessage.connection:type_name -> avoid.messages.ActionMessage.ConnType
	1, // 1: avoid.messages.ActionMessage.action:type_name -> avoid.messages.ActionMessage.Action
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_avoid_messages_proto_init() }
func file_avoid_messages_proto_init() {
	if File_avoid_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_avoid_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avoid_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_avoid_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_avoid_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_avoid_messages_proto_goTypes,
		DependencyIndexes: file_avoid_messages_proto_depIdxs,
		EnumInfos:         file_avoid_messages_proto_enumTypes,
		MessageInfos:      file_avoid_messages_proto_msgTypes,
	}.Build()
	File_avoid_messages_proto = out.File
	file_avoid_messages_proto_rawDesc = nil
	file_avoid_messages_proto_goTypes = nil
	file_avoid_messages_proto_depIdxs = nil
}
