syntax = "proto3";

package avoid.messages;

option go_package = "github.com/slackhq/nebula/avoid";

message ConnectionInfo {
  string uuid = 1;
  int64 version = 2;
  string name = 3;
  string ran = 4;
  string path = 5;
  string endpoint = 6;
  string network = 7;
  string relay = 8;
  string user = 9;
  int64 duration = 10;
  int64 lastseen = 11;
  int64 download = 12;
  int64 upload = 13;
  bool error = 14;
  string errMsg = 15;
}

message ActionRequest {
  string identifier = 1;
  avoid.messages.ActionMessage Action = 2;
  repeated string values = 3;
  string token = 4; // used for client
  int64 version = 5;
}

message ActionMessage {
  enum ConnType {
    NONE = 0;
    LIGHTHOUSE = 1;
    ENDPOINT = 2;
    RADIO = 3;
    NETWORK = 4;
    RELAY = 5;
  }
  enum Action {
    UNDEFINED = 0;
    MIGRATE = 1;
    DISCONNECT = 2;
    APPEND = 3;
    PRUNE = 4;
    FLUSH = 5;
    STATISTICS = 6;
  }

  ConnType connection = 1;
  Action action = 2;
  string uuid = 3;
  int64 version = 4;
}
