// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: avoid/relay.proto

package avoid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AvoidRelayClient is the client API for AvoidRelay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvoidRelayClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error)
}

type avoidRelayClient struct {
	cc grpc.ClientConnInterface
}

func NewAvoidRelayClient(cc grpc.ClientConnInterface) AvoidRelayClient {
	return &avoidRelayClient{cc}
}

func (c *avoidRelayClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidRelay/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avoidRelayClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, "/avoid.client.AvoidRelay/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvoidRelayServer is the server API for AvoidRelay service.
// All implementations must embed UnimplementedAvoidRelayServer
// for forward compatibility
type AvoidRelayServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthReply, error)
	mustEmbedUnimplementedAvoidRelayServer()
}

// UnimplementedAvoidRelayServer must be embedded to have forward compatible implementations.
type UnimplementedAvoidRelayServer struct {
}

func (UnimplementedAvoidRelayServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAvoidRelayServer) HealthCheck(context.Context, *HealthRequest) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAvoidRelayServer) mustEmbedUnimplementedAvoidRelayServer() {}

// UnsafeAvoidRelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvoidRelayServer will
// result in compilation errors.
type UnsafeAvoidRelayServer interface {
	mustEmbedUnimplementedAvoidRelayServer()
}

func RegisterAvoidRelayServer(s grpc.ServiceRegistrar, srv AvoidRelayServer) {
	s.RegisterService(&AvoidRelay_ServiceDesc, srv)
}

func _AvoidRelay_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidRelayServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidRelay/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidRelayServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvoidRelay_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvoidRelayServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/avoid.client.AvoidRelay/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvoidRelayServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvoidRelay_ServiceDesc is the grpc.ServiceDesc for AvoidRelay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvoidRelay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avoid.client.AvoidRelay",
	HandlerType: (*AvoidRelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AvoidRelay_Register_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AvoidRelay_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avoid/relay.proto",
}
