nebula_iface_name: neb1
nebula_network_domain: avoid-nebula
nebula_network_fqdn: avoid-nebula.org
install_user: rvn
overlay:
  'r0':
    ip: 192.168.0.100
    netmask: 24
  'r1':
    ip: 192.168.0.101
    netmask: 24
  'lh':
    ip: 192.168.0.1
    netmask: 24
  'ue':
    ip: 192.168.0.2
    netmask: 24
  'dst':
    ip: 192.168.0.200
    netmask: 24
config:
  'r0':
    interfaces:
    - ip: 10.0.0.100
      name: eth1
    - ip: 10.10.0.100
      name: eth2
  'r1':
    interfaces:
    - ip: 10.0.0.101
      name: eth1
    - ip: 10.11.0.101
      name: eth2
  'lh':
    interfaces:
    - ip: 10.0.0.1
      name: eth1
  'dst':
    interfaces:
    - ip: 10.0.0.200
      name: eth1
  'ue':
    interfaces:
    - ip: 10.10.0.2
      name: eth1
    - ip: 10.11.0.2
      name: eth2
