- hosts: all
  tasks:
    - name: get all addresses
      shell: ip -br addr | grep eth | grep -v eth0 | cut -d ' ' -f 1
      register: num_eths
      when: inventory_hostname in vars['config']

    - debug: var=num_eths

    - set_fact:
        ifaces: "{{ num_eths.stdout_lines }}"

    - name: flush interface
      command: ip addr flush {{ item.name }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces }}"
      become: yes
      when: inventory_hostname in vars['config']

    - name: set addr interface
      command: ip addr add {{ item.ip }}/24 dev {{ item.name }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces }}"
      become: yes
      when: inventory_hostname in vars['config']

    - name: set link up
      command: ip link set up {{ item.name }}
      with_items:
        - "{{ vars['config'][inventory_hostname].interfaces }}"
      become: yes
      when: inventory_hostname in vars['config']

- hosts: endpoints
  tasks:
    - name: add default for endpoints
      command: sudo ip route add {{ config[inventory_hostname].interfaces[0].route }} dev {{ config[inventory_hostname].interfaces[0].name }}
      become: yes

- hosts: relays
  tasks:
    - name: ipv4 forwarding
      shell: echo 1 > /proc/sys/net/ipv4/ip_forward
      become: yes

    - name: proxy arp
      shell: echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arp
      become: yes

# TODO: align with variables
- hosts: [lh]
  tasks:
    - name: add route back to ue
      shell: ip route add {{ item }}
      become: yes
      loop:
        - "10.10.0.0/24 via 10.0.0.100"
        - "10.11.0.0/24 via 10.0.0.100"
        - "10.12.0.0/24 via 10.0.0.101"
        - "10.13.0.0/24 via 10.0.0.101"
        - "10.14.0.0/24 via 10.0.0.102"
        - "10.15.0.0/24 via 10.0.0.102"
